package:
  name: ciftify
  version: "0.1.0"

source:
  git_rev: "v0.1.0"
  git_url: https://github.com/DESm1th/ciftify.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ciftify

about:
  home: https://github.com/DESm1th/ciftify
  license: MIT
  license_file: LICENSE
  summary: 'The tools of the Human Connectome Project (HCP) adapted for working with non-HCP datasets'
